version: "3.9"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: lyfeos_core
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file: [.env]
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./data:/data
      - ./labs:/labs
    depends_on:
      - vaultwarden
      - gitea

  nyxlab:
    image: python:3.12-slim
    container_name: lyfeos_nyxlab
    command: tail -f /dev/null
    volumes:
      - ./labs:/labs
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: lyfeos_vault
    restart: unless-stopped
    volumes:
      - ./vw_data:/data

  gitea:
    image: gitea/gitea:latest
    container_name: lyfeos_git
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./gitea:/data
